trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'
  major: 1
  minor: 2
  patch: $[counter('newminor190210', 0)]

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 3.0.100-preview5-011568
    
- script: |
    dotnet restore
    dotnet build -c $(buildConfiguration)
    dotnet pack src/Blazaco/Blazaco.csproj -c $(buildConfiguration) /p:PackageVersion=$(major).$(minor).$(patch) --output $(Build.ArtifactStagingDirectory) --no-build --no-restore
 
- task: PublishBuildArtifacts@1