  resources:
- repo: self

pool:
  vmImage: Hosted VS2017
  demands: msbuild

variables:
  buildConfiguration: 'release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.503'
  inputs:
    version: 2.1.503

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.3'
  inputs:
    versionSpec: 4.9.3

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: MSBuild@1
  displayName: 'Build solution **/*.sln'
  inputs:
    configuration: $(buildConfiguration)